<?php

namespace App\Imports;

use App\Bpkad;
use Maatwebsite\Excel\Concerns\ToModel;

class BpkadImport implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Bpkad([
            'tglgaji' => $row[0],
            'nip' => $row[1],
            'nama' => $row[2],
            'glrbelakang' => $row[3],
            'glrdepan' => $row[4],
            'kdjenkel' => $row[5],
            'tempatlhr' => $row[6],
            'tgllhr' => $row[7],
            'agama' => $row[8],
            'pendidikan' => $row[9],
            'tmtcapeg' => $row[10],
            'tmtskmt' => $row[11],
            'mkgolt' => $row[12],
            'blgolt' => $row[13],
            'tmtkgb' => $row[14],
            'tmtkgbyad' => $row[15],
            'bup' => $row[16],
            'nodosir' => $row[17],
            'kdcabtaspen' => $row[18],
            'kdssbp' => $row[19],
            'kdskpd' => $row[20],
            'kdsatker' => $row[21],
            'alamat' => $row[22],
            'kddati4' => $row[23],
            'kddati3' => $row[24],
            'kddati2' => $row[25],
            'kddati1' => $row[26],
            'notelp' => $row[27],
            'npwp' => $row[28],
            'niplama' => $row[29],
            'kodebyr' => $row[30],
            'norek' => $row[31],
            'kdhitung' => $row[32],
            'tmtberlaku' => $row[33],
            'taperum' => $row[34],
            'kdjnstrans' => $row[35],
            'jistri' => $row[36],
            'janak' => $row[37],
            'kdstapeg' => $row[38],
            'tmtstop' => $row[39],
            'kdpangkat' => $row[40],
            'masker' => $row[41],
            'prsngapok' => $row[42],
            'tmttabel' => $row[43],
            'kdeselon' => $row[44],
            'kdfungsi' => $row[45],
            'kdguru' => $row[46],
            'kdstruk' => $row[47],
            'kdberas' => $row[48],
            'kdlangka' => $row[49],
            'kdterpencil' => $row[50],
            'kdtkd' => $row[51],
            'kdtjkhusus' => $row[52],
            'kdkorpri' => $row[53],
            'kdkoperasi' => $row[54],
            'kdirdhata' => $row[55],
            'gapok' => $row[56],
            'tjistri' => $row[57],
            'tjanak' => $row[58],
            'tjtpp' => $row[59],
            'tjeselon' => $row[60],
            'tjfungsi' => $row[61],
            'tjstruk' => $row[62],
            'tjguru' => $row[63],
            'tjlangka' => $row[64],
            'tjtkd' => $row[65],
            'tjterpencil' => $row[66],
            'tjkhusus' => $row[67],
            'tjberas' => $row[68],
            'tjpajak' => $row[69],
            'tjaskes' => $row[70],
            'tjumum' => $row[71],
            'tjkk' => $row[72],
            'tjkm' => $row[73],
            'tbulat' => $row[74],
            'kotor' => $row[75],
            'piwp' => $row[76],
            'paskes' => $row[77],
            'ppajak' => $row[78],
            'pbulog' => $row[79],
            'ptaperum' => $row[80],
            'psewa' => $row[81],
            'phutang' => $row[82],
            'pkorpri' => $row[83],
            'pirdhata' => $row[84],
            'pkoperasi' => $row[85],
            'pjkk' => $row[86],
            'pjkm' => $row[87],
            'potongan' => $row[88],
            'bersih' => $row[89],
            'catatan' => $row[90],
            'nu' => $row[91],
            'hal' => $row[92],
            'kdstawin' => $row[93],
            'nmsatker' => $row[94],
            'nmskpd' => $row[95],
            'noktp' => $row[96],

        ]);
    }
}
